### ISSUE TITLE
[Bug] Cannot find the Broker in Linux when using multiprocessing

### ISSUE THREAD

**Issue by plimy** [GMLC-TDC/pyhelics#30]
The code included in this runs on Windows
it doesn't on Linux
For some reason I do not understand, the Process is unable to connect to the broker.

I believe that the issue is caused by the difference in implementation between Multiprocessing on Windows and Linux, and some interaction that PyHelics has with that difference in implementation.

However I do not know the actual cause.

### OS
OS: Windows 10 Enterprise
Version: 20H2
Build: 19042.1165
Experience: Windows Feature Experience Pack 120.2212.3530.0

OS: Ubuntu
Version: 20.04.2 LTS

### Software 
python: 3.8.10
pyhelics: 3.0.0.0

## Code
```Python
from multiprocessing import Process
import multiprocessing
import helics as h
import time

class GoldenModel():
    def __init__(self):
        deltat = 0.01
        fedinitstring = "--federates=1"
        fedinfo = h.helicsCreateFederateInfo()
        h.helicsFederateInfoSetCoreName(fedinfo, "Golden Federate")
        h.helicsFederateInfoSetCoreTypeFromString(fedinfo, "zmq")
        h.helicsFederateInfoSetCoreInitString(fedinfo, fedinitstring)
        h.helicsFederateInfoSetTimeProperty(fedinfo, h.helics_property_time_delta, deltat)
        self.vfed = h.helicsCreateValueFederate("Golden Federate", fedinfo)
        self.pub = h.helicsFederateRegisterGlobalTypePublication(self.vfed, "Golden", "double", "")

    def __del__(self):
        h.helicsFederateDisconnect(self.vfed)
        h.helicsFederateFree(self.vfed)
        pass

    def exec(self):
        h.helicsFederateEnterExecutingMode(self.vfed)
        goldenRatio = 1.6180339887
        currentTime = 0
        for t in range(0, 10):
            val = goldenRatio + t
            currentTime = h.helicsFederateRequestTime(self.vfed, t+1)
            h.helicsPublicationPublishDouble(self.pub, val)
            time.sleep(1)
        
def golden_model():
    p = GoldenModel()
    p.exec()
    pass


if __name__ == '__main__':
    multiprocessing.freeze_support()

    initstring = "-f 2"
    broker = h.helicsCreateBroker("zmq", "", initstring)
    isconnected = h.helicsBrokerIsConnected(broker)
    if (isconnected == 1):
        print("Broker Connected")


    print("Making Golden Process")
    golden_process = Process(
        target=golden_model,
        name="GoldenModel",
        args=(),
    )
    print("Starting Golden Process")
    golden_process.start()

    fedinitstring = "--federates=1"
    deltat = 0.01
    fedinfo = h.helicsCreateFederateInfo()
    h.helicsFederateInfoSetCoreName(fedinfo, fedinitstring)
    h.helicsFederateInfoSetTimeProperty(fedinfo, h.helics_property_time_delta, deltat)
    vfed = h.helicsCreateValueFederate("Reciever Federate", fedinfo)
    golden_sub = h.helicsFederateRegisterSubscription(vfed, "Golden", "")
    h.helicsFederateEnterExecutingMode(vfed)

    currentTime = -1
    last_golden_value = 0
    while currentTime <= 100:
        currentTime = h.helicsFederateRequestTime(vfed, 100)
        temp = h.helicsInputGetDouble(golden_sub)
        if (temp != last_golden_value):
            last_golden_value = temp
            print("Recieved Value {}".format(temp))

    print("Finished")
    h.helicsFederateDisconnect(vfed)
    h.helicsFederateFree(vfed)
    h.helicsCloseLibrary()

```

## Error that occurs running on a Linux machine.
```Bash
Broker Connected
Making Golden Process
Starting Golden Process
[2021-08-19 09:16:56.099] [console] [warning] commWarning||Golden Federate (0)[t=-98763.2]::zmq broker connection timed out, trying again (2)
[2021-08-19 09:16:56.099] [console] [warning] commWarning||Golden Federate (0)[t=-98763.2]::sending message to tcp://127.0.0.1:23405
[2021-08-19 09:17:16.122] [console] [error] commERROR||Golden Federate (0)[t=-98763.2]::zmq broker connection timed out after trying 5 times (2)
[2021-08-19 09:17:16.122] [console] [error] commERROR||Golden Federate (0)[t=-98763.2]::receiver connection failure
Process GoldenModel:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "goldenmultiprocessor.py", line 37, in golden_model
    p.exec()
  File "goldenmultiprocessor.py", line 24, in exec
    self.vfed = h.helicsCreateValueFederate("Golden Federate", fedinfo)
  File "/home/gang/.local/lib/python3.8/site-packages/helics/capi.py", line 3204, in helicsCreateValueFederate
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode
```

**Comment by kdheepak** [comment]
Presumably this is the same issue as this one: https://github.com/GMLC-TDC/HELICS/issues/2061. I don't think this is an issue with the pyhelics interface, so I'll close it over here.

**Comment by nightlark** [comment]
Based on the problem being with the behavior of multiprocessing on different operating systems, I think this is more relevant to pyhelics (users).

What happens if you use `multiprocessing.set_start_method('spawn')` as shown in the example on https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods? That should make Linux match the default behavior on Windows/macOS. I was able to reproduce the bug on WSL and that fixed it.

An alternate idea if you want to try to keep using the default multiprocessing behavior would be to use the multiprocessing module to start the broker in its own child process, which would avoid the forked process effectively duplicating an already running broker.

**Comment by plimy** [comment]
That works really well. Thank you!

**Comment by nightlark** [comment]
Issues with multiprocessing using fork could also occur on macOS using Python versions prior to 3.8 (when multiprocessing switched from `fork` to `spawn` as the default for macOS).

**Comment by trevorhardy** [comment]
Closing out as this issue appears to be resolved.
